#!/usr/bin/env node

var es = require("event-stream");
var JSONStream = require("JSONStream");

process.stdin.setEncoding("utf8");

process.stdin
  .pipe(JSONStream.parse(process.argv[2]))
  .pipe(
    es.mapSync(function (document) {
      return document;
    })
  )
  .pipe(JSONStream.stringify())
  .pipe(process.stdout);
