#!/bin/bash

set -eo pipefail

mongo $MONGO_URL --eval "db.$1.ensureIndex({geometry: '2dsphere'}).note"
mongo $MONGO_URL --eval "db.$1.ensureIndex({'$2': 'text'}).note"

cat | mongoimport \
	--uri $MONGO_URL \
  --jsonArray \
  --upsert \
  --upsertFields $2 \
  --collection $1 \
  --db boundaries
